# Setup
title:  A@A Template Documentation
description: A demo of the template documents
email: 			adobeatadobe@adobe.com
baseurl: 	  "/pages/aaa/gh-pages-boilerplate" # the subpath of your site, e.g. /blog
theme: jekyll-theme-cayman # theme from jekyll github account
google_analytics: [Your Google Analytics tracking ID]
repository: aaa/gh-pages-boilerplate # location of your repository
markdown: redcarpet # markdown engine

# About/contact
author:
  name:       Adobe@Adobe
  url:        http://www.adobeatadobe.com